posts/urls.py
from django.urls import path
from .views import post_comment_create, like_unlike_post, PostDeleteView, PostUpdateView


app_name = 'posts'


urlpatterns = [
    path('', post_comment_create, name="main-post"),
    path('liked', like_unlike_post, name="like-post"),
    path('<pk>/delete/', PostDeleteView.as_view(), name="post-delete"),
    path('<pk>/update/', PostUpdateView.as_view(), name="post-update"),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('', views.ProfileListView.as_view(), name="all-profiles-views"),
    path('<slug>/', views.ProfileDetialsView.as_view(), name="profile-detail"),
    path('myprofile/', views.my_profile_view, name="my-profile"),
    path('myinvites/', views.invites_received_view, name="my-invites"),
    path('to-invite/', views.invite_profiles_list_view, name="invite-profiles"),
    path('sent-invite/', views.send_invitation, name="send-invite"),
    path('remove-invite/', views.remove_from_friends, name="remove-invite"),
    path('accept-invite/', views.accept_inv, name="accept-invite"),
    path('reject-invite/', views.reject_inv, name="reject-invite" ),
]

social_net/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from .views import home_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name="home-view"),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.db.models import Q
from django.shortcuts import reverse


class ProfileManager(models.Manager):
    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile  = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))
        accepted = set([])
        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.receiver)
                accepted.add(rel.sender)

        available = [profile for profile in profiles if profile not in accepted]
        return available

    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles


class Profile(models.Model):
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="No bio", max_length=300)
    email = models.EmailField(max_length=100, blank=True)
    country = models.CharField(max_length=50, blank=True)
    avatar = models.ImageField(default='avatar.png', upload_to='avatars/')
    friends = models.ManyToManyField(User, blank=True, related_name='Friends')
    slug = models.SlugField(unique=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, blank=True)
    
    objects = ProfileManager()
    
    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%Y-%m-%d')}"
    
    def get_absolute_url(self):
        return reverse('profiles:profile-detail', kwargs={'slug': self.slug})
    
    def get_friends(self):
        return self.friends.all()
    
    def get_friend_no(self):
        return self.friends.all().count()
    
    def get_posts_no(self):
        return self.posts.all().count()

    def get_all_author_posts(self):
        return self.posts.all()

    def get_likes_given_no(self):
        likes = self.like_set.all()
        total_liked = 0
        for item in likes:
            if item.value == 'Like':
                total_liked += 1
        return total_liked

    def get_liked_recieved_no(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked

    __initial_first_name = None
    __initial_last_name = None
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name =self.first_name
        self.__initial_last_name =self.last_name
        
    def save(self, *args, **kwargs):
        ex = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug == '':
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_random_code()))
                    ex = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args , **kwargs)


STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)

class RelationshipManager(models.Manager):
    def invitations_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status="send")
        return qs


class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, blank=True)

    objects = RelationshipManager()

    def __str__(self):
        return f'{self.sender}-{self.receiver}-{self.status}'

profiles/forms.py
from django import forms
from .models import Profile


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'bio', 'avatar']

profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Profile, Relationship
from .forms import ProfileModelForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User
from django.db.models import Q


class ProfileDetialsView(DetailView):
    model = Profile
    template_name = 'profiles/detail.html'
    
    def get_object(self,*args , **kwargs):
        slug = self.kwargs.get('slug')
        profile = Profile.objects.get(slug=slug)
        return profile
    
    def get_context_data(self,*args ,**kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
            
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['posts'] = self.get_object().get_all_author_posts()
        context['len_posts'] = True if len(self.get_object().get_all_author_posts()) > 0 else False
        return context


def my_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False
    
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True
    
    context = { 
        'profile' : profile ,
        'form': form,
        'confirm': confirm
    }
    return render(request, 'profiles/myprofile.html', context)


def invites_received_view(request):
    receiver = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invitations_received(receiver)
    results = list(map(lambda x: x.sender, qs))
    is_empty = False
    if len(results) == 0:
        is_empty = True
        
    context = {
        'qs': results,
        'is_empty': is_empty 
    }
    
    return render(request, 'profiles/my_invites.html', context)
    

def invite_profiles_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles_to_invite(user)
    context = {'qs': qs }
    return render(request, 'profiles/invite_list.html', context)


def accept_inv(request):
    if request.method == 'POST':
        user = request.user
        pk = request.POST.get('profile_pk')
        receiver  = Profile.objects.get(user=user)
        sender = Profile.objects.get(pk=pk)
        
        rel = get_object_or_404(Relationship, receiver=receiver, sender=sender)
        if rel.status == 'send':
            rel.status = "accepted"
            rel.save()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-invites')
        

def reject_inv(request):
    if request.method == 'POST':
        user = request.user
        pk = request.POST.get('profile_pk')
        receiver  = Profile.objects.get(user=user)
        sender = Profile.objects.get(pk=pk)
        
        rel = get_object_or_404(Relationship, receiver=receiver, sender=sender)
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-invites')


def profiles_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles(user)
    context = {'qs': qs }
    return render(request, 'profiles/profile_list.html', context)


class ProfileListView(ListView):
    model = Profile
    template_name  = 'profiles/profile_list.html'
    context_object_name = 'qs'
    
    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
            
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True
        return context


def send_invitation(request):
    if request.method == 'POST':
        user = request.user
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)
        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile')


def remove_from_friends(request):
    if request.method == 'POST':
        user = request.user
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)
        
        rel = Relationship.objects.get(
            Q(sender=sender) & Q(receiver=receiver) | Q(sender=receiver) & Q(receiver=sender)
        )
        
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile')

profiles/templates/profiles/detail.html
{% extends 'base.html'%}
{% block title %} - Profile Details {% endblock title %}
{% block content %}
<!-- <div class="ui segment"> -->
  <div class="ui grid" style="margin-top: 10px;">
    <div class="row">
      <div class="four wide column">
        <img class="ui medium rounded image" src='{{ object.avatar.url }}' >
        <h2>{{ object.user|title }}</h2>
        <div class="ui vertical fluid menu">
          <div class="item">
            Posts <div class="ui label">{{ object.get_posts_no }}</div>
          </div>
          <div class="item">
            Likes Given <div class="ui label">{{ object.get_likes_given_no }}</div>
          </div>
          <div class="item">
            Likes Recieved <div class="ui label">{{ object.get_liked_recieved_no }}</div>
          </div>
          <div class="item">
            Friends <div class="ui label">{{ object.get_friend_no }}</div>
          </div>
        </div>


        <div style="padding:5px;">
          {% if object.user not in rel_receiver and object.user not in rel_sender %}
          <form action="{% url 'profiles:send-invite' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="profile_pk" value='{{ object.pk }}' />
            <button type="submit" class="ui positive basic button"><i class="plus square icon"></i>Add to friend</button>
          </form>
          {% endif %}

          {% if object.user in rel_receiver and request.user not in object.friends.all %}
            <button class="ui disabled button"><i class="user icon"></i>Waiting for approve</button>
          {% endif %}
            
          {% if request.user in object.friends.all %}
          <form action="{% url 'profiles:remove-invite' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="profile_pk" value='{{ object.pk }}' />
            <button type="submit" class="ui negative basic button"><i class="minus square icon"></i>Remove from friend</button>
          </form>
          {% endif %}
        </div>

      </div>
      <div class="twelve wide column">
        {% if len_posts %}
        
          {% for post in posts %}
          <div class="segment ui fluid">
            {{ post.content }}
          </div>
          {% endfor %}
        {% else %}
        <h2>No post of this user</h2>

        {% endif %}
          
      </div>
    </div>
  </div>
<!-- </div> -->
{% endblock content %}
  

profiles/templates/profiles/invite_list.html
{% extends 'base.html'%}
{% block title %} - Invite Friends {% endblock title %}

  {% block content %}
    
    {% if is_empty %}
      <h3>You have no invites</h3>
    {% else %}
    <ul>
      {% for obj in qs %}
       <div class="ui segment">

      {% endfor %}
    </ul>
    {% endif %}


  </div>
  {% endblock content %}
    

profiles/templates/profiles/my_invites.html
{% extends 'base.html'%}

{% block title %} - Invites{% endblock title %}
  
  {% block content %}
    
  {% if is_empty %}
    <h3>You have no invites</h3>
  {% endif %}

      
      {% for obj in qs %}
        <div class="ui segment">
          <div class="ui grid">
            <div class="row">
              <div class="three wide column">
                <img class="ui small circular image"  src='{{ obj.avatar.url }}' />
              </div>
              <div class="thirteen wide column">
                <h4>{{ obj.user|title }}</h4>
                <p>{{ obj.bio }}</p>
                  <a type="submit" class="ui positive basic button mb-5">See Ptofile</a>

                  <form action="{% url 'profiles:accept-invite' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value='{{ obj.pk }}' />
                    <button type="submit" class="ui button positive mb-5">
                      <i class="icon check"></i>Accept Invite
                    </button>
                  </form>

                  <form action="{% url 'profiles:reject-invite' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value='{{ obj.pk }}' />
                    <button type="submit" class="ui button negative mb-5">
                      <i class="icon close"></i> Reject Invite
                    </button>
                  </form>

              </div>
            </div>
          </div>
        </div>

      {% endfor %}
        
  
  {% endblock content %}
    

profiles/templates/profiles/myprofile.html
{% extends "base.html" %}
{% block title %} - Profiles{% endblock title %}

{% block content %}
  <div class="ui modal mymodal">
    <i class="close icon"></i>
    <div class="header">
      Update Profile
    </div>
    <div class="image content">
      <div class="ui medium image">
        <img src="{{ profile.avatar.url }}">
      </div>
      <div class="description">
        <div class="ui header">Provide new info !!!</div>
        <form action='' method="post" class="ui form" enctype="multipart/form-data">
          {% csrf_token %}
            {{ form.as_p }}

            <div class="actions">
              <button type="submit" class="ui positive right labeled icon button">
                Update
                <i class="checkmark icon"></i>
              </button>
            </div>
        </form>

      </div>
    </div>
  </div>

  <div class="ui segment"> 
    {% if confirm %}
    <div class="ui green message">Profile Updated !!!</div>
    {% endif %}

    <h2>{{ request.user|title }}</h2>
    <div class="ui grid">
      <div class="row">
        <div class="six wide column">
          <img class="ui medium rounded image" src="{{ profile.avatar.url }}">
          <div class="row mt-5" style="margin-top: 20px !important;">
            <button class="ui secondary button" id="modal-btn">Update Your Profile</button>
          </div>
        </div>
        <div class="ten wide column">
          <table class="ui table">
            <tbody>
              <tr>
                <td>First Name</td>
                <td>{{ profile.first_name|title }}</td>
              </tr>
              <tr>
                <td>Last Name</td>
                <td>{{ profile.last_name|title }}</td>
              </tr>
              <tr>
                <td>Bio</td>
                <td>{{ profile.bio }}</td>
              </tr>
              <tr>
                <td>No of Friends</td>
                <td>{{ profile.get_friend_no }}</td>
              </tr>

              <tr>
                <td>Friends</td>
                <td>
                  <ul class="friends_list">
                    {% for friend in profile.get_friends %}
                      <li>{{ friend }}</li>
                    {% endfor %}
                  </ul>
                </td>
              </tr>

              <tr>
                <td>No of Posts</td>
                <td>{{ profile.get_posts_no }}</td>
              </tr>

              <tr>
                <td>No of likes given</td>
                <td>{{ profile.get_likes_given_no }}</td>
              </tr>

              <tr>
                <td>No of likes received</td>
                <td>{{ profile.get_liked_recieved_no }}</td>
              </tr>

            </tbody>

          </table>
        </div>
      </div>
    </div>
  </div>
    <!-- <button class="ui secondary button" id="modal-btn">Update Your Profile</button> -->


{% endblock content %}


{% block script_js %}
{% endblock script_js %}
  

profiles/templates/profiles/profile_list.html
{% extends 'base.html'%}
{% block title %} - All Profiles{% endblock title %}
  
  {% block content %}
  {% if is_empty %}
    <h2>No profiles to interact with !!!</h2>
  {% endif %}
  
  {% for obj in object_list %}
    <div class="ui segment ">
      <div class="ui grid">
        <div class="row">
          <div class="three wide column">
            <img class="ui small circular image"  src='{{ obj.avatar.url }}' />
          </div>
          <div class="thirteen wide column">
            <h3>{{ obj.user|title }}</h3>
            <p>{{ obj.bio }}</p>
            <a class="ui button primary" href="{{ obj.get_absolute_url }}">View Profile</a> 
            <div style="margin-bottom: 10px;"></div>

            {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
            <form action="{% url 'profiles:send-invite' %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="profile_pk" value='{{ obj.pk }}' />
              <button type="submit" class="ui positive basic button"><i class="plus square icon"></i>Add to friend</button>
            </form>
            {% endif %}

            {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
              <button class="ui disabled button"><i class="user icon"></i>Waiting for approve</button>
            {% endif %}
              
            {% if request.user in obj.friends.all %}
            <form action="{% url 'profiles:remove-invite' %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="profile_pk" value='{{ obj.pk }}' />
              <button type="submit" class="ui negative basic button"><i class="minus square icon"></i>Remove from friend</button>
            </form>
            {% endif %}

          </div>

        </div>
      </div>
    </div>
  {% endfor %}
    

  {% endblock content %}
    